### ISSUE TITLE
Crash/respring

### ISSUE THREAD

**Issue by hey101** [inoahdev/LaunchInSafeMode#1]
First off, awesome idea for a tweak. This will be a lifesaver for some apps when they update before tweaks update. 
As to the issue anytime I force touch an app, it instantly resprings my device. I'm on an iPhone 6s running iOS 10.2. If I disable the tweak then force touch works fine.

**Comment by inoahdev** [comment]
Yea, I've had others email me about the same crash. I've submitted an update to the BIgBoss repo that should be up in about 2 days. In the meantime, I've added the build submitted (v1.0.1) to the Releases section, see if that works for you

**Comment by suclogger** [comment]
I've installed the newest 1.0.1, but it still causes device to respring from time to time when I use force touch.
iPhone 6s  iOS 10.2

**Comment by inoahdev** [comment]
@suclogger Can you provide a crash log for this? Thanks

**Comment by suclogger** [comment]
Actually it works quit well today.
But it causes crash everytime force-touch a self-signed app.I'm sure you can reproduce that too.
Still, it's  a really great tweak!

**Comment by inoahdev** [comment]
Ah thanks! :)
The self-signed apps (such as Yalu, and the myriad of random apps I've created at one point in Xcode and exported to my iPhone) all seem to run fine when launched in Safe Mode. Can you provide the crash logs for your crashes, they may be a different issue entirely.

**Comment by suclogger** [comment]
My crash log when I tab yalu:
https://gist.githubusercontent.com/suclogger/2f317d59b7f9c19d316c8146366f7a8a/raw/1026941136d1b5853a4e77c0179e2591c964137a/gistfile1.txt

**Comment by inoahdev** [comment]
Can you try [this](https://www.dropbox.com/s/5qpsl1f9kmx00w2/com.inoahdev.launchinsafemode_1.0.2-7%2Bdebug_iphoneos-arm.deb?dl=0) build? A file should be created in /User (or /var/mobile) called LaunchInSafeMode_Logs.txt. Send me the file once you experience another crash when force touching on an application.

**Comment by suclogger** [comment]
This build works great with  self-signed app too.

**Comment by inoahdev** [comment]
That's weird. I haven't actually modified any code, besides adding some logging function calls here and there.

**Comment by suclogger** [comment]
I purged the debug build ,
switched back to the Cydia 1.0.1 version,
and self-signed app began to crash again.

**Comment by inoahdev** [comment]
Ok, try [this](https://www.dropbox.com/s/blj54fgptml4ls7/com.inoahdev.launchinsafemode_1.0.2-8%2Bdebug_iphoneos-arm.deb?dl=0) build. Reduced the logging to just one log

**Comment by suclogger** [comment]
![image](https://cloud.githubusercontent.com/assets/8472155/26438370/30e5089e-4155-11e7-82fe-90b09cbf680b.png)

Not intent to be funny, but this build just don't crash neither.

**Comment by inoahdev** [comment]
Ok, this may be an issue of optimizations, try [this](https://www.dropbox.com/s/t3ew00fa8p6rshi/com.inoahdev.launchinsafemode_1.0.2-9%2Bdebug_iphoneos-arm.deb?dl=0) build, compiled without optimizations
And [this](https://www.dropbox.com/s/pbowwibbp891bhy/com.inoahdev.launchinsafemode_1.0.2_iphoneos-arm.deb?dl=0) build, compiled with optimizations, and tell me which one crashes

**Comment by inoahdev** [comment]
@suclogger Wait, before installing the builds above, can you send the file at /User/LaunchInSafeMode_Logs.txt?

**Comment by suclogger** [comment]
I've tried both build with or without optimizations and both worked fine, and "/User/LaunchInSafeMode_Logs.txt" is an empty file.
I guess you can release the 1.0.2 version to cydia.
Meanwhile I would stick to this debug version and send further crash logs(if any).
Thanks for your quick reply.
