### ISSUE TITLE
iOS 11 support??

### ISSUE THREAD

**Issue by theb1g0ne** [inoahdev/LaunchInSafeMode#3]
Really missing this tweak since I’ve updated recently. Willing to work on it myself as well or offer any help/testing needed.

**Comment by inoahdev** [comment]
Sorry, didn't see this earlier. Must have gotten lost in my notifications
Kirb said he would work on it, but any work on this would be greatly appreciated.

I'm currently not jailbroken on iOS 11, so I can't update this

**Comment by theb1g0ne** [comment]
Hey! I just saw this reply now too! I guess I don't get email notifications, so I'll make sure to turn them on. Any status on the progress so far?

**Comment by inoahdev** [comment]
iOS 11 Support was added in commit 7717f98484e1f95c95c52094e390ae7dba65e34c
